# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 449a13b176df4fc1f5effdd87ece3fbcbff666411a62df22eb02d05202d40ac87aae06243a878a9ff0ec3a0c43f3e3df23c268286dd4266b64d4528d585fa854

test:
  secret_key_base: b364b9836a727d82d65e7488ba83d9affa0074903779e3072b26a1fa4121d10a9ab017b1410c0ae59ca8a953b2ab970eb4fe1e3bf2db09fecec47c946992d58d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
